name: Keepalive (Prevent Schedule Disable)

on:
  schedule:
    - cron: '43 3 * * 1'   # 每周一 03:43 UTC 与主任务错开并避开整点
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Jitter (random delay up to 5m)
        run: |
          secs=$(( RANDOM % 300 ))
          echo "Sleeping $secs seconds..."
          sleep $secs

      - name: Update KEEPALIVE file if needed
        id: update_keepalive
        run: |
          set -euo pipefail
          TODAY=$(date -u +%Y-%m-%d)
          FILE=KEEPALIVE
          echo "Last run UTC date: $TODAY"
          if [ ! -f "$FILE" ]; then
            echo "$TODAY" > "$FILE"
            echo "created=true" >> $GITHUB_OUTPUT
          else
            LAST=$(cat "$FILE" || true)
            if [ "$LAST" != "$TODAY" ]; then
              echo "$TODAY" > "$FILE"
              echo "created=true" >> $GITHUB_OUTPUT
            else
              echo "No change needed"
            fi
          fi

      - name: Commit & push
        if: steps.update_keepalive.outputs.created == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add KEEPALIVE
          git commit -m "chore: keepalive $(date -u +%Y-%m-%d)"
          git push
