name: Patch LXGW WenKai Fonts

on:
  schedule:
    - cron: '0 0 * * *' # 每天定时检查，您可以根据需求调整
  workflow_dispatch: # 手动触发工作流

jobs:
  check-and-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Fetch latest LXGW WenKai release
        id: fetch-release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/lxgw/LxgwWenKai/releases/latest | jq -r .tag_name)
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Check if version already patched
        run: |
          if git tag | grep -q "$LATEST_RELEASE"; then
            echo "Version $LATEST_RELEASE already patched."
            exit 0
          fi

      - name: Download LXGW WenKai fonts
        run: |
          mkdir fonts
          wget -O fonts/lxgw-wenkai.zip https://github.com/lxgw/LxgwWenKai/releases/download/$LATEST_RELEASE/LXGWWenKai.zip
          unzip fonts/lxgw-wenkai.zip -d fonts

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontforge python3 python3-pip
          pip3 install argparse

      - name: Download and set up Font Patcher
        run: |
          wget -O FontPatcher.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip
          unzip FontPatcher.zip -d FontPatcher
          chmod +x FontPatcher/font-patcher

      - name: Patch fonts
        run: |
          mkdir patched-fonts
          for font in fonts/*.ttf; do
            ./FontPatcher/font-patcher --complete "$font" -o patched-fonts/
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: patched-fonts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
