name: Patch LXGW WenKai Fonts

on:
  schedule:
    - cron: '0 0 * * *' # 每天定时检查，您可以根据需求调整
  workflow_dispatch: # 手动触发工作流

jobs:
  check-and-patch:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 获取最新的 LXGW WenKai 版本并检查是否已处理
        id: fetch-release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/lxgw/LxgwWenKai/releases/latest | jq -r .tag_name)
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

          if git tag | grep -q "$LATEST_RELEASE"; then
            echo "版本 $LATEST_RELEASE 已处理。"
            exit 0
          fi

      - name: 安装所有依赖项
        run: |
          sudo apt-get update
          sudo apt-get install -y fontforge python3 python3-pip python3-fontforge tree

      - name: 下载 LXGW WenKai 字体并显示文件结构
        run: |
          mkdir fonts
          wget -q -O fonts/lxgw-wenkai.tar.gz https://github.com/lxgw/LxgwWenKai/releases/download/$LATEST_RELEASE/lxgw-wenkai-$LATEST_RELEASE.tar.gz
          tar -xzvf fonts/lxgw-wenkai.tar.gz -C fonts
          tree fonts -L 2

      - name: 下载并设置 Font Patcher
        run: |
          wget -q -O FontPatcher.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip
          unzip FontPatcher.zip -d FontPatcher
          chmod +x FontPatcher/font-patcher

      - name: 对字体进行补丁处理
        run: |
          mkdir patched-fonts
          for font in fonts/**/*.ttf; do
            ./FontPatcher/font-patcher  --complete --no-progressbars --quiet "$font" -o patched-fonts/
            
          done

      - name: 打包字体为 tar.gz 和 zip
        run: |
          tar -czvf patched-fonts.tar.gz -C patched-fonts .
          zip -r patched-fonts.zip patched-fonts

      - name: 创建 GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            patched-fonts.tar.gz
            patched-fonts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
