name: Patch LXGW WenKai Fonts

on:
  schedule:
    - cron: '0 0 * * *' # Daily scheduled check, adjust as needed
  workflow_dispatch: # Manually trigger workflow

jobs:
  check-and-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Get latest LXGW WenKai version and check if already processed
        id: fetch-release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/lxgw/LxgwWenKai/releases/latest | jq -r .tag_name)
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

          if git tag | grep -q "$LATEST_RELEASE"; then
            echo "Version $LATEST_RELEASE already processed."
            exit 0
          fi

      - name: Install all dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontforge python3 python3-pip python3-fontforge tree

      - name: Download LXGW WenKai fonts and display file structure
        run: |
          mkdir fonts
          wget -q -O fonts/lxgw-wenkai.tar.gz https://github.com/lxgw/LxgwWenKai/releases/download/$LATEST_RELEASE/lxgw-wenkai-$LATEST_RELEASE.tar.gz
          tar -xzvf fonts/lxgw-wenkai.tar.gz -C fonts
          tree fonts -L 2

      - name: Download and set up Font Patcher
        run: |
          wget -q -O FontPatcher.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip
          unzip FontPatcher.zip -d FontPatcher
          chmod +x FontPatcher/font-patcher

      - name: Create output directory
        run: |
          mkdir -p lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}

  patch-fonts:
    needs: check-and-patch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        font: ["$(find fonts -name '*.ttf')"]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Patch the font
        run: |
          ./FontPatcher/font-patcher --complete --quiet --careful "${{ matrix.font }}" -o lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}/

  package-and-release:
    needs: patch-fonts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Package fonts as tar.gz and zip
        run: |
          tree lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }} -L 2
          tar -czvf lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}.tar.gz -C . lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}
          zip -r lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}.zip lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Original LXGW WenKai release: https://github.com/lxgw/LxgwWenKai/releases/tag/${{ env.LATEST_RELEASE }}"
          tag_name: ${{ env.LATEST_RELEASE }}
          files: |
            lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}.tar.gz
            lxgw-wenkai-nerd-${{ env.LATEST_RELEASE }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
